properly quote variables, posix fixes

diff --git a/src/brmgr b/src/brmgr
--- a/src/brmgr
+++ b/src/brmgr
@@ -3,17 +3,27 @@
 
 set -e
 
-function die() {
-	echo "$(basename ${0}):" $@
+die() {
+	echo "$(basename "${0}"):" "$@"
 	exit 2
 }
 
 rundir="/run/brmgr"
+bridge=""
+addr=""
+addr6=""
+dhcp_range=""
+dhcp_max=""
+dhcp_conffile=""
+dhcp_hostsfile=""
+domain=""
 etc="${rundir}/${1}"
+
 shift
 
-[ -r "$etc" ] && . "$etc" || die \
-	"could not read configuration file: $etc"
+test -s "$etc" \
+	&& . "$etc" \
+	|| die "could not read configuration file: $etc"
 
 domain_arg=""
 test -z "$domain" || domain_arg="-s $domain -s /$domain/"
@@ -21,7 +31,7 @@ ipv6_arg=""
 test -z "$addr6" || ipv6_arg="--dhcp-range=${addr6},ra-only --listen-address ${addr6}"
 
 exec dnsmasq $domain_arg -k -o -z -u nobody \
-	-i ${bridge} -I lo -a ${addr} \
+	-i "${bridge}" -I lo -a "${addr}" \
 	--conf-file="${dhcp_conffile}" --dhcp-hostsfile="${dhcp_hostsfile}" \
-	$ipv6_arg -F "${dhcp_range}" -X ${dhcp_max} -K --dhcp-no-override \
-	-l /var/lib/misc/dnsmasq.${bridge}.leases $@
+	$ipv6_arg -F "${dhcp_range}" -X "${dhcp_max}" -K --dhcp-no-override \
+	-l "/var/lib/misc/dnsmasq.${bridge}.leases" "$@"
diff --git a/src/brmgr-pre b/src/brmgr-pre
--- a/src/brmgr-pre
+++ b/src/brmgr-pre
@@ -4,17 +4,26 @@
 set -e
 
 rundir="/run/brmgr"
+bridge=
+bridge_mac=
+network=
+addr=
+netmask=
+network=
+addr6=
+netmask6=
+network6=
 
-function die() {
-        echo "$(basename ${0}):" $@
+die() {
+        echo "$(basename "${0}"):" "$@"
         exit 1
 }
 
-etc="/etc/brmgr.conf" && test -z "$1" || \
-	etc="/etc/brmgr/${1}.conf"
-
-[ -r "$etc" ] && . "$etc" || die \
-	"could not read configuration file: $etc"
+test -n "$1" \
+	&& etc="/etc/brmgr/${1}.conf" \
+	&& test -s "$etc" \
+	&& . "$etc" \
+	|| die "could not read configuration file: $etc"
 
 test "$1" = "$bridge" || die \
 	"bridge configuration does not match filename"
@@ -22,33 +31,33 @@ test "$1" = "$bridge" || die \
 test -n "$bridge" -a -n "$addr" -a -n "$netmask" -a -n "$network" || die \
 	"missing config variable(s)"
 
-test ! -d /sys/class/net/${bridge} || die \
+test ! -d /sys/class/net/"${bridge}" || die \
 	"bridge already exists, not starting"
 
-ip link add dev ${bridge} type bridge || die \
+ip link add dev "${bridge}" type bridge || die \
 	"missing bridge support in kernel"
 
 echo 1 > /proc/sys/net/ipv4/ip_forward
 echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
-echo 0 > /proc/sys/net/ipv6/conf/${bridge}/autoconf
-echo 0 > /proc/sys/net/ipv6/conf/${bridge}/accept_dad || true
+echo 0 > /proc/sys/net/ipv6/conf/"${bridge}"/autoconf
+echo 0 > /proc/sys/net/ipv6/conf/"${bridge}"/accept_dad || true
 
-ip addr add ${addr}/${netmask} dev ${bridge}
-test -z "${addr6}" || ip -6 addr add ${addr6}/${netmask6} dev ${bridge}
-test -z "${bridge_mac}" || ip link set dev ${bridge} address ${bridge_mac}
-ip link set ${bridge} up
+ip addr add "${addr}/${netmask}" dev "${bridge}"
+test -z "${addr6}" || ip -6 addr add "${addr6}/${netmask6}" dev "${bridge}"
+test -z "${bridge_mac}" || ip link set dev "${bridge}" address "${bridge_mac}"
+ip link set "${bridge}" up
 
 ipt_lock="-w"
 iptables -w -l -n > /dev/null 2>&1 || ipt_lock=""
 
-iptables $ipt_lock -I INPUT -i ${bridge} -p udp --dport 67 -j ACCEPT
-iptables $ipt_lock -I INPUT -i ${bridge} -p tcp --dport 67 -j ACCEPT
-iptables $ipt_lock -I INPUT -i ${bridge} -p udp --dport 53 -j ACCEPT
-iptables $ipt_lock -I INPUT -i ${bridge} -p tcp --dport 53 -j ACCEPT
-iptables $ipt_lock -I FORWARD -i ${bridge} -j ACCEPT
-iptables $ipt_lock -I FORWARD -o ${bridge} -j ACCEPT
-iptables $ipt_lock -t nat -A POSTROUTING -s ${network} ! -d ${network} -j MASQUERADE
-iptables $ipt_lock -t mangle -A POSTROUTING -o ${bridge} -p udp -m udp \
+iptables $ipt_lock -I INPUT -i "${bridge}" -p udp --dport 67 -j ACCEPT
+iptables $ipt_lock -I INPUT -i "${bridge}" -p tcp --dport 67 -j ACCEPT
+iptables $ipt_lock -I INPUT -i "${bridge}" -p udp --dport 53 -j ACCEPT
+iptables $ipt_lock -I INPUT -i "${bridge}" -p tcp --dport 53 -j ACCEPT
+iptables $ipt_lock -I FORWARD -i "${bridge}" -j ACCEPT
+iptables $ipt_lock -I FORWARD -o "${bridge}" -j ACCEPT
+iptables $ipt_lock -t nat -A POSTROUTING -s "${network}" ! -d "${network}" -j MASQUERADE
+iptables $ipt_lock -t mangle -A POSTROUTING -o "${bridge}" -p udp -m udp \
 	--dport 68 -j CHECKSUM --checksum-fill
 test -z "${network6}" || ip6tables $ipt_lock -t nat -A POSTROUTING \
 	-s "${network6}" ! -d "${network6}" -j MASQUERADE
